tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "asdf"
brew "bat"
brew "exa"
brew "fd"
brew "fswatch"
brew "gh"
brew "git"
brew "gnupg"
brew "java"
brew "jq"
brew "lcov"
brew "mackup"
brew "mas"
brew "multi-git-status"
brew "pidof"
brew "pinentry-mac"
brew "plantuml"
brew "pyenv"
brew "pyenv-virtualenv"
brew "sd"
brew "starship"
brew "tldr"
brew "yq"
brew "zplug"

cask "arc"
cask "bitwarden"
cask "bruno"
cask "chromedriver"
cask "devonthink" # remove once migrated to Obsidian
cask "docker"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "google-drive"
cask "keeper-password-manager"
cask "iterm2"
cask "mysqlworkbench"
cask "notion"
cask "obsidian"
cask "raycast"
cask "slack"
cask "viscosity"
cask "visual-studio-code"
cask "zoom"

mas "Things 3", id: 904280696
mas "Todoist", id: 585829637
