alias ddev='dart run dart_dev'
alias pbr='dart run build_runner'
alias pubg='dart pub get --no-precompile'
alias pubu='dart pub upgrade --no-precompile'
alias dv='dart run dependency_validator'
alias repub='pubclean; pubg'
alias pubclean='rm -rf .dart_tool/ && echo "Removed .dart_tool/"; rm .packages && echo "Removed .packages"; pubcleanlock'
alias pubcleanlock='git ls-files pubspec.lock --error-unmatch &>/dev/null && echo "Not removing pubspec.lock - it is tracked" || (rm pubspec.lock && echo "Removed pubspec.lock")'
alias ldart="$LOCAL_DART_SDK_BIN/dart"
alias lpub="$LOCAL_DART_SDK_BIN/pub"
