# Include profile-specific private repos.

{{ if eq .profile "work" -}}
[".local/share/chezmoi-work"]
    type = "git-repo"
    url = "git@github.com:ekweible/dotfiles_profile.workiva.git"
    refreshPeriod = "168h"
    [".local/share/chezmoi-work".pull]
        args = ["--ff-only"]
{{- end }}
