class JOBS:
    CHANGE_SHELL = 'Change shell to zsh'
    CONFIGURE_SETTINGS = 'Configure iterm2 and system settings'
    IMPORT_GPG_KEYS = 'Import GPG keys'
    INSTALL_FONTS = 'Install fonts'
    INSTALL_NVM = 'Install NVM'
    LINK_DOTFILES = 'Generate & link all dotfiles'
    OPEN_NON_CASKED_APPS = 'Open non-casked app download pages'
    SYNC_GIT = 'Sync git repositories'
    UPDATE_SUBMODULES = 'Install/update all dotfiles git submodules'
    UPGRADE_BREW_CASKS = 'Install/upgrade brew casks'
    UPGRADE_BREW_PACKAGES = 'Install/upgrade brew packages'
    UPGRADE_GEM_RAKES = 'Install/upgrade ruby gems'
